version: '3.7'
services:
  client:
    image: node:lts
    working_dir: /app
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules
    ports:
      - "3000:3000"
    command: >
      sh -c "npm install && npm run start"
    depends_on:
      - server
    networks:
      - network
  server:
    image: node:lts
    working_dir: /app
    volumes:
      - ./server:/app
      - ./server/node_modules:/app/node_modules
    ports:
      - "5001:5001"
    command: >
      sh -c "npm install -g @nestjs/cli && npm install && npm run start:dev"
    depends_on:
      - db
    networks:
      - network
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: task_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@olimp.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - network

volumes:
  db-data:
  pgadmin-data:
  node_modules:
  
networks:
  network:
